[package]
name = "lsm"
version = "0.1.0"
authors = ["Igor Katson <igor_katson@symantec.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
memmap = "^0.7"
bincode = "^1"
serde = {version = "*", features = ["derive"]}
flate2 = "^1"
lru = "^0.4"