[package]
name = "lsm"
version = "0.1.0"
authors = ["Igor Katson <igor_katson@symantec.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
memmap = "^0.7"
bincode = "^1"
serde = {version = "*", features = ["derive"]}
flate2 = "^1"
lru = "^0.4"
byteorder = "^1"
bytes = "*"
snap = "^0.2"
nix = "^0.5"
parking_lot = "^0.10"
num_cpus = "^1"

[dev-dependencies]
criterion = "^0.3"
chashmap = "*"
rand = {version = "^0.7", features=["small_rng"]}
crossbeam = "^0.7"
rayon = "^1.3"

[[bench]]
name = "sstable_implementations"
harness = false